# Generated by Django 6.0.6 on 2026-06-22 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aadhaar_front', models.FileField(blank=True, null=True, upload_to='kyc/aadhaar/')),
                ('aadhaar_back', models.FileField(blank=True, null=True, upload_to='kyc/aadhaar/')),
                ('pan', models.FileField(blank=True, null=True, upload_to='kyc/pan/')),
                ('selfie', models.FileField(blank=True, null=True, upload_to='kyc/selfie/')),
                ('bank_account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('review_remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kycs', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
